name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  Build-and-Tests:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: running infrastructure
      run: |
        cd infrastructure
        docker-compose up -d
        sleep 2s            
    - name: Setup JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'adopt'
        architecture: x64
    - name: Run the Maven verify phase
      run: mvn --batch-mode --update-snapshots verify
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.6
      with:
        reports: 'target/site/jacoco/jacoco.xml'
        reporttypes: 'Html;Badges'
        targetdir: 'docs' # REQUIRED # The directory where the generated report should be saved.
        historydir: 'docs/history'
        sourcedirs: '' 
    - name: Push Report
      uses: EndBug/add-and-commit@v4
      with:
        add: 'docs/*'
        message: "Coverage Report ${{github.sha}}"
        ref: 'gh-pages' 
        remove: ''  
      if: ${{ github.ref == 'refs/heads/main' }}
    - name: Publish Unit Test Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Maven Tests
        path: target/surefire-reports/*.xml
        reporter: java-junit
        fail-on-error: true
